#!/bin/bash

SAMPLE_RATE_SPS=$1
FREQ_MHZ=$2
TYPE=0 # float32 IQ
VGA_GAIN=5
MIXER_GAIN=99
LNA_GAIN=99
SENSITIVITY_GAIN=8

airspy_rx -h $SENSITIVITY_GAIN -r /tmp/capture.iq -t $TYPE -a $SAMPLE_RATE_SPS -f $FREQ_MHZ
