amdemod_new: amdemod_new.c
	gcc -o amdemod_new amdemod_new.c -lm

amdemod: amdemod.c
	gcc -o amdemod amdemod.c -lsndfile -lfftw3f -lm

#acarsdec: acarsdec.c
#	gcc -o acarsdec acarsdec.c -lsndfile -lfftw3f -lm
